"""empty message

Revision ID: cfa1e64bb9bf
Revises: 1eb9d061b873
Create Date: 2023-06-13 23:25:46.300135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfa1e64bb9bf'
down_revision = '1eb9d061b873'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('make', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('model', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('year', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('color', sa.String(length=200), nullable=True))
        batch_op.drop_column('name')
        batch_op.drop_column('email')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.drop_column('color')
        batch_op.drop_column('year')
        batch_op.drop_column('model')
        batch_op.drop_column('make')

    # ### end Alembic commands ###
